# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
        harsh: 
            algorithm: plaintext
            

    role_hierarchy:
        ROLE_ARTIST: ROLE_USER
        ROLE_BLOGGER: ROLE_USER
        ROLE_BUYER: ROLE_USER 
        ROLE_SUPERARTIST: ROLE_ARTIST
        ROLE_ADMIN:  [ROLE_BLOGGER, ROLE_ARTIST]
       

    providers:
        our_db_provider:
            entity:
                class: AppBundle:Usuario
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                login_path: login
                check_path: login
                default_target_path: homepage
            logout:
                path:   /logout
                target: homepage
            anonymous: ~
            provider: our_db_provider
            
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/addCV,  roles: [ROLE_ARTIST, ROLE_ADMIN] }
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
